apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-internet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: check-internet-app
  template:
    metadata:
      labels:
        app: check-internet-app
    spec:
      containers:
        - name: check-internet-app
          image: registry.digitalocean.com/check-internet/check-internet-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: registry-check-internet
