apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-kube-app-hpa
specs:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deplyoyment
    name: hello-kube-app
  miniReplicas: 2
  maxReplicas: 5
  metrics:
    - type: resources
      resources:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50