apiVersion: v1
kind: Service
metadata:
  name: check-internet-service
spec:
  selector:
    app: check-internet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
