apiVersion: v1
kind: Service
metadata:
  name: check-internet-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"  # Distributes traffic across 2 nodes
spec:
  selector:
    app: check-internet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
